#!/bin/sh

SDCARD_DEV=
MASS_STORAGE_FILE=/sys/devices/virtual/android_usb/android0/f_mass_storage/lun/file
SDCARD_MOUNT_PATH=/media/card

ls /dev | grep "mmc*"
if test ! $? -eq 0
then
  echo "" > ${MASS_STORAGE_FILE}
  exit 1
fi

if [ `ls /dev | grep mmcblk0p1 | wc -l` -ge 1 ]; then
  SDCARD_DEV=/dev/mmcblk0p1
else
  if [ `ls /dev | grep mmcblk0 | wc -l` -ge 1 ]; then
    SDCARD_DEV=/dev/mmcblk0
  else
    exit 1
  fi
fi

echo "Change SD-card access mode = usb"

df | grep ${SDCARD_MOUNT_PATH}
if test $? -eq 0
then
    umount ${SDCARD_MOUNT_PATH}
fi

echo "${SDCARD_DEV}" > ${MASS_STORAGE_FILE}

exit $?

