#!/bin/sh

test -x /usr/bin/make_swap || exit 0

case "$1" in
  start)
    echo "Starting make_swap."
    /usr/bin/make_swap &
    ;;
  stop)
    echo "Stopping make_swap."
    pkill -9 make_swap
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/swap_on {start|stop|restart|force-reload}"
    exit 1
esac

exit 0
